# Generated by Django 5.2.6 on 2025-09-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('balls', 'Balls'), ('socks', 'Socks'), ('gloves', 'Gloves'), ('backpacks', 'Backpacks'), ('soccer cleats', 'Soccer Cleats')], default='jersey', max_length=20),
        ),
    ]
